[toolchain]

[features]
seeds = true
skip-lint = false

[programs.devnet]
box_minter = "FPAzYdh8rdSRSXYQBneqwniqWGn3out5eQg2n1qyotxd"

[programs.localnet]
box_minter = "FPAzYdh8rdSRSXYQBneqwniqWGn3out5eQg2n1qyotxd"

[programs.mainnet]
box_minter = "DWZD5yiLRWXUuN7Gp7CLF7jQAdhpWf7uxwawe2H16r5v"

[programs.testnet]
box_minter = "D6HxewzSWiFc4yVupdRQT1G4mFw4K7rJKhiV3SEoUju9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/ivan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
